services:
  mongodb:
    restart: unless-stopped
    image: mongo:latest
    container_name: mongodb-payment
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGOADMIN}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
    networks:
      - backend
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  payment:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment
    environment:
      - MONGODB_URL=${MONGOURL}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - PORT = 3003
      - API_VERSION = ${API_VERSION}
      - FRONTEND_URL = ${FRONTEND_URL}
      - NODE_ENV = ${NODE_ENV}
    depends_on:
      - mongodb
    networks:
      - backend
    ports:
      - "3003:3003"

volumes:
  mongo-data:

networks:
  backend:
    driver: bridge
