apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: mongodb