apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: payment-svc
  name: payment-svc
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  selector:
    io.kompose.service: payment-svc
