apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o kubernetes/
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: payment-svc
  name: payment-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: payment-svc
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes/
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: payment-svc
    spec:
      containers:
        - env:
            - name: API_PREFIX
              value: /api/v1
            - name: AZURE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: AZURE_ACCOUNT_NAME
            - name: AZURE_ANALYTICS_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: AZURE_ANALYTICS_CONTAINER_NAME
            - name: AZURE_IMAGES_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: AZURE_IMAGES_CONTAINER_NAME
            - name: AZURE_SAS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: AZURE_SAS_TOKEN
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: JWT_SECRET
            - name: KAFKA_HOST
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: KAFKA_HOST
            - name: MONGOURL
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: MONGOURL
            - name: NODE_ENV
              value: production
            - name: FRONTEND_URL
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: FRONTEND_URL
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: STRIPE_API_KEY
          image: ghcr.io/fis2425/payment-svc:latest
          name: payment-svc
          ports:
            - containerPort: 3003
              protocol: TCP
      restartPolicy: Always